export const REQUEST_DATA = "REQUEST_DATA"
export const REQUEST_CATEGORY = "REQUEST_CATEGORY"
export const FILTER_GOODS = "FILTER_GOODS"
// Create post
export const CREATE_GOOD = 'CREATE_GOOD';
export const CREATE_GOOD_SUCCESS = 'CREATE_GOOD_SUCCESS';
export const CREATE_GOOD_FAILURE = 'CREATE_GOOD_FAILURE';
export const RESET_NEW_POST = 'RESET_NEW_POST';

export const DELETE_GOOD = 'DELETE_GOOD';
export const DELETE_GOOD_SUCCESS = 'DELETE_GOOD_SUCCESS';
export const DELETE_GOOD_FAILURE = 'DELETE_GOOD_FAILURE';
export const RESET_DELETED_GOOD = 'RESET_DELETED_GOOD';

export const CHANGE_GOOD = 'CHANGE_GOOD';
export const CHANGE_GOOD_SUCCESS = 'CHANGE_GOOD_SUCCESS';
export const CHANGE_GOOD_FAILURE = 'CHANGE_GOOD_FAILURE';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

export const FETCH_CATEGORY_NEW = 'FETCH_CATEGORY_NEW';